from __future__ import annotations
from typing import Any
import re
import random
from src.satquery.registry import ModelResult

def _get_aoi_bounds(aoi: dict | None) -> tuple[float, float, float, float]:
    """Returns (min_lng, min_lat, max_lng, max_lat) from an AOI."""
    if aoi and "bounds" in aoi:
        b = aoi["bounds"]
        return b["west"], b["south"], b["east"], b["north"]
    if aoi and "geometry" in aoi and aoi["geometry"]["type"] == "Polygon":
        coords = aoi["geometry"]["coordinates"][0]
        lngs = [c[0] for c in coords]
        lats = [c[1] for c in coords]
        return min(lngs), min(lats), max(lngs), max(lats)
    # Default fallback: central Ahmedabad region
    return 72.50, 23.05, 72.55, 23.09

def _get_deterministic_polygon(seed_text: str, bounds: tuple[float, float, float, float], size_fraction=0.1) -> list[list[list[float]]]:
    """Generates a rectangular polygon inside the bounds, deterministically seeded by text and rounded bounds."""
    min_lng, min_lat, max_lng, max_lat = bounds
    
    # Round bounds to 3 decimal places for seed stability (so tiny map movements don't jitter evidence)
    seed_string = f"{seed_text}_{round(min_lng, 3)}_{round(min_lat, 3)}_{round(max_lng, 3)}_{round(max_lat, 3)}"
    r = random.Random(seed_string)
    
    width = max_lng - min_lng
    height = max_lat - min_lat
    
    poly_w = width * size_fraction
    poly_h = height * size_fraction
    
    # Random origin inside the bounds, leaving room for the polygon
    x0 = min_lng + r.random() * (width - poly_w)
    y0 = min_lat + r.random() * (height - poly_h)
    
    x1 = x0 + poly_w
    y1 = y0 + poly_h
    
    return [[[x0, y0], [x1, y0], [x1, y1], [x0, y1], [x0, y0]]]

def get_vqa_scenario(query: str, aoi: dict | None = None) -> ModelResult:
    """Single Image VQA"""
    q = query.lower()
    answer = "The scene contains mixed land cover features, including some built-up areas and natural vegetation."
    summary = "Analysis indicates a diverse landscape with residential areas and natural flora."
    observations = {
        "Land Cover": ["Built-up: Moderate to high concentration", "Vegetation: Distributed across peripheral areas"],
        "Spatial Distribution": ["Dense built-up regions concentrated toward the eastern sector"]
    }
    
    if re.search(r"build|urban|house|infrastructure|road", q):
        answer = "Major infrastructure includes a dense urban residential network, visible primary road arteries, and scattered commercial structures."
        summary = "The analyzed scene shows a mixed urban landscape dominated by built-up infrastructure and road networks."
        observations = {
            "Infrastructure": ["Primary road arteries visible", "Dense urban residential networks"],
            "Distribution": ["Commercial structures scattered across the scene"]
        }
    elif re.search(r"water|river|lake|sea|ocean", q):
        answer = "A significant water body is visible, consistent with a river channel bordered by riparian vegetation."
        summary = "A prominent water feature dominates the scene, bordered by natural vegetation."
        observations = {
            "Water": ["Significant river channel detected"],
            "Surroundings": ["Riparian vegetation present along banks"]
        }
    elif re.search(r"vegetation|forest|tree|crop|agriculture", q):
        answer = "Land cover is predominantly agricultural fields interspersed with patches of dense forest canopy."
        summary = "The scene is predominantly rural with agricultural fields and forest patches."
        observations = {
            "Vegetation": ["Agricultural fields dominate", "Patches of dense forest canopy present"],
            "Structure": ["Interspersed land use"]
        }

    return ModelResult(
        answer=answer,
        confidence=0.85,
        summary=summary,
        observations=observations,
        demo_metadata={
            "scenario": "Single Image VQA",
            "modality": "Optical (RGB)",
            "limitations": "This result was generated by the deterministic demonstration layer and does not represent live ML inference."
        }
    )

def get_caption_grounding_scenario(query: str, aoi: dict | None = None) -> ModelResult:
    """Caption/Grounding"""
    q = query.lower()
    
    if "describe" in q or "scene" in q:
        return ModelResult(
            answer="A high-resolution optical scene featuring a central water body bounded by urban development on the west and agricultural plots on the east.",
            confidence=0.94,
            summary="A detailed scene with mixed urban, water, and agricultural elements.",
            observations={"Features": ["Central water body", "Urban development to the west", "Agricultural plots to the east"]},
            demo_metadata={
                "scenario": "Captioning",
                "modality": "Optical (RGB)",
                "limitations": "Deterministic demonstration layer."
            }
        )

    target_label = "Region of interest"
    coords = []
    
    bounds = _get_aoi_bounds(aoi)
    
    if "water" in q or "river" in q or "lake" in q:
        target_label = "Water body"
        coords = _get_deterministic_polygon("water", bounds, 0.15)
    elif "build" in q or "urban" in q or "road" in q:
        target_label = "Built-up area"
        coords = _get_deterministic_polygon("urban", bounds, 0.1)
    else:
        target_label = "Identified feature"
        coords = _get_deterministic_polygon("feature", bounds, 0.12)

    evidence = {
        "geojson": {
            "type": "FeatureCollection",
            "features": [{
                "type": "Feature",
                "properties": {
                    "label": target_label,
                    "confidence": 0.95
                },
                "geometry": {
                    "type": "Polygon",
                    "coordinates": coords
                }
            }]
        }
    }
    
    return ModelResult(
        answer=f"Located the requested spatial feature: {target_label.lower()}.",
        confidence=0.95,
        summary=f"Successfully grounded {target_label.lower()} in the image.",
        observations={"Target Feature": [target_label], "Evidence Regions": ["1 spatial region identified"]},
        evidence=evidence,
        demo_metadata={
            "scenario": "Feature Grounding",
            "modality": "Optical (RGB)",
            "limitations": "Deterministic demonstration layer. Bounding polygon is a fixture."
        }
    )

def get_change_scenario(query: str, aoi: dict | None = None) -> ModelResult:
    """Bi-temporal Change"""
    q = query.lower()
    
    bounds = _get_aoi_bounds(aoi)
    
    if "deforest" in q or "vegetation" in q or "tree" in q:
        answer = "Significant vegetation loss detected in the eastern sector, likely indicating land clearing activities."
        summary = "Detected a notable reduction in vegetation coverage."
        label = "Deforestation"
        coords = _get_deterministic_polygon("deforest", bounds, 0.15)
        observations = {"Detected Change": ["Vegetation loss (Deforestation)"], "Estimated Change Magnitude": ["High"], "Affected Area": ["Eastern sector"]}
    elif "water" in q or "flood" in q:
        answer = "Surface water extent has increased significantly, consistent with flooding or seasonal inundation in the low-lying areas."
        summary = "Detected a notable increase in surface water extent."
        label = "Water expansion"
        coords = _get_deterministic_polygon("flood", bounds, 0.2)
        observations = {"Detected Change": ["Water expansion (Flooding)"], "Estimated Change Magnitude": ["High"], "Affected Area": ["Low-lying areas"]}
    else:
        answer = "New built-up development and urban expansion are detected in the central region, indicating recent construction."
        summary = "Detected new urban infrastructure development."
        label = "Urban expansion"
        coords = _get_deterministic_polygon("urban_expansion", bounds, 0.1)
        observations = {"Detected Change": ["Urban expansion"], "Estimated Change Magnitude": ["Moderate"], "Affected Area": ["Central region"], "Change Direction": ["Increase in built-up coverage"]}

    evidence = {
        "geojson": {
            "type": "FeatureCollection",
            "features": [{
                "type": "Feature",
                "properties": {
                    "label": label,
                    "type": "change_polygon",
                    "confidence": 0.89,
                    "note": "Demo scenario estimate"
                },
                "geometry": {
                    "type": "Polygon",
                    "coordinates": coords
                }
            }]
        }
    }
    
    return ModelResult(
        answer=answer,
        confidence=0.89,
        summary=summary,
        observations=observations,
        evidence=evidence,
        demo_metadata={
            "scenario": "Bi-temporal Change",
            "modality": "Optical Pairs (T1, T2)",
            "limitations": "Deterministic demonstration layer. Change polygon is a fixture."
        }
    )

def get_fusion_scenario(query: str, aoi: dict | None = None) -> ModelResult:
    """Optical + SAR Fusion"""
    return ModelResult(
        answer="Optical observations identify spectral patterns associated with vegetation and surface water. SAR backscatter provides complementary structural information, increasing confidence in built-up regions.",
        confidence=0.96,
        summary="Fused analysis reveals high confidence in structural mapping.",
        observations={
            "Optical Observations": ["Identified spectral patterns for vegetation and water"],
            "SAR Observations": ["Backscatter confirms structural built-up areas", "Confirms water surfaces through low backscatter"],
            "Cross-Modal Agreement": ["High alignment between optical water indices and SAR dark regions"],
            "Final Fused Interpretation": ["Accurate mapping of built-up areas vs natural features"]
        },
        demo_metadata={
            "scenario": "Optical + SAR Fusion",
            "modality": "Multi-modal (Optical RGB + SAR VV)",
            "limitations": "Deterministic demonstration layer. No real feature extraction performed."
        }
    )
